In [1]:
#Europe LGBT Survey Analysis
#Questions to consider
#make datasets specific for each dataset?

#Daily Life Survey specific 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dailylife = pd.read_csv("Datasets/LGBT_Survey_DailyLife.csv")
dailylife.head()

,CountryCode,subset,question_code,question_label,answer,percentage,notes
0,Austria,Lesbian,b1_a,"In your opinion, how widespread is offensive l...",Very widespread,8,NaN
1,Austria,Lesbian,b1_a,"In your opinion, how widespread is offensive l...",Fairly widespread,34,NaN
2,Austria,Lesbian,b1_a,"In your opinion, how widespread is offensive l...",Fairly rare,45,NaN
3,Austria,Lesbian,b1_a,"In your opinion, how widespread is offensive l...",Very rare,9,NaN
4,Austria,Lesbian,b1_a,"In your opinion, how widespread is offensive l...",Don`t know,4,[0]

In [3]:
#analyze by question, group by question given to participants. 
#maybe do select countries?

#Find out countries that were listed
countries = dailylife.groupby("CountryCode").count()
countries

#Pick 3-5 countries, one from each region
#Pick Spain, UK, Germany, Denmark, Romania

,subset,question_code,question_label,answer,percentage,notes
CountryCode,,,,,,
Austria,1180,1180,1180,1180,1180,440
Average,1184,1184,1184,1184,1184,16
Belgium,1179,1179,1179,1179,1179,429
Bulgaria,1170,1170,1170,1170,1170,640
Croatia,1163,1163,1163,1163,1163,625
Cyprus,1158,1158,1158,1158,1158,1054
Czech Republic,1179,1179,1179,1179,1179,460
Denmark,1175,1175,1175,1175,1175,492
Estonia,1152,1152,1152,1152,1152,889
Finland,1180,1180,1180,1180,1180,296
France,1180,1180,1180,1180,1180,223
Germany,1184,1184,1184,1184,1184,92
Greece,1170,1170,1170,1170,1170,473
Hungary,1172,1172,1172,1172,1172,521
Ireland,1177,1177,1177,1177,1177,568
Italy,1176,1176,1176,1176,1176,228
Latvia,1161,1161,1161,1161,1161,849
Lithuania,1160,1160,1160,1160,1160,749
Luxembourg,1171,1171,1171,1171,1171,992
Malta,1143,1143,1143,1143,1143,924
Netherlands,1181,1181,1181,1181,1181,375
Poland,1184,1184,1184,1184,1184,484
Portugal,1180,1180,1180,1180,1180,538
Romania,1176,1176,1176,1176,1176,632
Slovakia,1172,1172,1172,1172,1172,670
Slovenia,1169,1169,1169,1169,1169,839
Spain,1184,1184,1184,1184,1184,297
Sweden,1180,1180,1180,1180,1180,294
United Kingdom,1180,1180,1180,1180,1180,207

In [4]:
#Find out questions listed
questions = pd.DataFrame(dailylife.loc[:, ["question_code", "question_label"]]);
#questions.groupby("question_label").value_count()
questions = questions["question_label"].value_counts()
questions
#Select specific questions since there are so many of them to choose

For each of the following types of discrimination, could you please specify whether, in your opinion, it is very rare, fairly rare, fairly widespread or very widespread in the country where you live?                                                                         1450
All things considered, how satisfied would you say you are with your life these days? *                                                                                                                                                                                         1412
Have you been open about you being L, G, B or T? *                                                                                                                                                                                                                               870
how did you come to know about this survey?                                                                                                                                                                                                                                      859
In the country where you live, do you consider yourself to be part of any of the following? *                                                                                                                                                                                    849
In your opinion, in the country where you live, how widespread is discrimination because a person is Lesbian?                                                                                                                                                                    725
In your opinion, how widespread are expressions of hatred and aversion towards lesbian, gay, bisexual and/or transgender in public in the country where you live?                                                                                                                725
In your opinion, how widespread are positive measures to promote respect for the human rights of lesbian, gay or bisexual people in the country where you live? *                                                                                                                725
You have received poorer services than others (eg in restaurants, shops) - In the last six months, in your day-to-day life, how often have any of the following things happened to you because you are or are assumed to be L,G,B,T                                              725
In your opinion, in the country where you live, how widespread is discrimination because a person is Transgender?                                                                                                                                                                725
In your opinion, how widespread is public figures in politics, business, sports, etc being open about themselves being lesbian, gay, bisexual and/or transgender in the country where you live?                                                                                  725
In terms of your civil status in the country where you live, are you *                                                                                                                                                                                                           725
In your opinion, how widespread are positive measures to promote respect for the human rights of transgender people in the country where you live? *                                                                                                                             725
In your opinion, in the country where you live, how widespread is discrimination because a person is Gay?                                                                                                                                                                        725
In your opinion, in the country where you live, how widespread is discrimination because a person is Bisexual?                                                                                                                                                                   725
In your opinion, how many people know that you are L, G, B or T? Neighbours?                                                                                                                                                                                                     725
In your opinion, how widespread are assaults and harassment against lesbian, gay, bisexual and/or transgender people in the country where you live?                                                                                                                              725
In your opinion, how widespread are casual jokes in everyday life about lesbian, gay, bisexual and/or transgender people in the country you live?                                                                                                                                725
In your opinion, how many people know that you are L, G, B or T? Work colleagues / schoolmates?                                                                                                                                                                                  725
In your opinion, how widespread is same-sex partners holding hands in public in the country where you live?                                                                                                                                                                      725
You have been treated with less courtesy than other people - In the last six months, in your day-to-day life, how often have any of the following things happened to you because you are or are assumed to be lesbian, gay, bisexual and/or transgender?                         725
In your opinion, how widespread is heterosexual partners holding hands in public in the country where you live?                                                                                                                                                                  725
In your opinion, how widespread is offensive language about lesbian, gay, bisexual and/or transgender people by politicians in the country where you live?                                                                                                                       725
In your opinion, how many people know that you are L, G, B or T? Family members (other than your partner(s))?                                                                                                                                                                    725
In your opinion, how many people know that you are L, G, B or T? Friends?                                                                                                                                                                                                        725
You have been treated with less respect than other people - In the last six months, in your day-to-day life, how often have any of the following things happened to you because you are or are assumed to be lesbian, gay, bisexual and/or transgender?                          725
Recognition of same-sex partnerships across the European Union - What would allow you to be more comfortable living as a lesbian, gay or bisexual person in the country where you live?                                                                                          696
What would allow you to be more comfortable living as a lesbian, gay or bisexual person in the country where you live? The possibility to marry and/or register a partnership?                                                                                                   696
What would allow you to be more comfortable living as a lesbian, gay or bisexual person in the country where you live? Anti-discrimination policies referring to sexual orientation at the workplace?                                                                            696
What would allow you to be more comfortable living as a lesbian, gay or bisexual person in the country where you live? National authorities who promote the rights of lesbian, gay and bisexual people?                                                                          696
What would allow you to be more comfortable living as a lesbian, gay or bisexual person in the country where you live? Public figures in politics, business, sports, etc openly speaking in support of lesbian, gay and bisexual people?                                         696
What would allow you to be more comfortable living as a lesbian, gay or bisexual person in the country where you live? Better acceptance of differences in sexual orientations by religious leaders?                                                                             696
What would allow you to be more comfortable living as a lesbian, gay or bisexual person in the country where you live? Measures implemented at school to respect lesbian, gay and bisexual people?                                                                               696
What would allow you to be more comfortable living as a lesbian, gay or bisexual person in the country where you live? The possibility to foster / adopt children?                                                                                                               696
What would allow you to be more comfortable living as a lesbian, gay or bisexual person in the country where you live? Training of public servants (eg police, teachers) on the rights of lesbian, gay and bisexual people?                                                      696
4 levels of being open about LGBT background *                                                                                                                                                                                                                                   580
To how many people among the following groups are you open about yourself being L, G, B or T? Immediate superior/head of department                                                                                                                                              580
To how many people among the following groups are you open about yourself being L, G, B or T? Neighbours ?                                                                                                                                                                       580
To how many people among the following groups are you open about yourself being L, G, B or T? Family members (other than your partner(s))?                                                                                                                                       580
To how many people among the following groups are you open about yourself being L, G, B or T ? Friends ?                                                                                                                                                                         580
To how many people among the following groups are you open about yourself being L, G, B or T? Medical staff / health care providers?                                                                                                                                             580
Does your current partner know that you are L, G, B or T?                                                                                                                                                                                                                        580
To how many people among the following groups are you open about yourself being L, G, B or T? Work colleagues / schoolmates?                                                                                                                                                     580
To how many people among the following groups are you open about yourself being L, G, B or T? Customers, clients, etc at work?                                                                                                                                                   580
What best describes your current situation in the country where you live *                                                                                                                                                                                                       435
Have you ever moved to an EU country (and also taken up local residence) together with your same-sex partner, since you married or registered your partnership?                                                                                                                  294
Are you a parent or legal guardian of a child (or children)?                                                                                                                                                                                                                     290
Do any children (under the age of 18) live in your household?                                                                                                                                                                                                                    290
Is someone in the household a parent or legal guardian of a child (or children)?                                                                                                                                                                                                 290
In the country where you have moved to (taken u p residence), have you or your partner been denied or restricted access to any benefits or services that would have been available for a different-sex spouse or partner because of you having a same-sex partner or spouse?     272
Name: question_label, dtype: int64

In [5]:
#Measure by question and pick by country

#Select by country
nations_chosen = ["Spain", "United Kingdom", "Romania"]
picked_nations = dailylife[dailylife.CountryCode.isin(nations_chosen)]
picked_nations

,CountryCode,subset,question_code,question_label,answer,percentage,notes
225,Spain,Lesbian,b1_a,"In your opinion, how widespread is offensive l...",Very widespread,11,NaN
226,Spain,Lesbian,b1_a,"In your opinion, how widespread is offensive l...",Fairly widespread,35,NaN
227,Spain,Lesbian,b1_a,"In your opinion, how widespread is offensive l...",Fairly rare,44,NaN
228,Spain,Lesbian,b1_a,"In your opinion, how widespread is offensive l...",Very rare,7,NaN
229,Spain,Lesbian,b1_a,"In your opinion, how widespread is offensive l...",Don`t know,2,NaN
230,Spain,Gay,b1_a,"In your opinion, how widespread is offensive l...",Very widespread,8,NaN
231,Spain,Gay,b1_a,"In your opinion, how widespread is offensive l...",Fairly widespread,29,NaN
232,Spain,Gay,b1_a,"In your opinion, how widespread is offensive l...",Fairly rare,46,NaN
233,Spain,Gay,b1_a,"In your opinion, how widespread is offensive l...",Very rare,16,NaN
234,Spain,Gay,b1_a,"In your opinion, how widespread is offensive l...",Don`t know,2,NaN
235,Spain,Bisexual women,b1_a,"In your opinion, how widespread is offensive l...",Very widespread,12,NaN
236,Spain,Bisexual women,b1_a,"In your opinion, how widespread is offensive l...",Fairly widespread,36,NaN
237,Spain,Bisexual women,b1_a,"In your opinion, how widespread is offensive l...",Fairly rare,41,NaN
238,Spain,Bisexual women,b1_a,"In your opinion, how widespread is offensive l...",Very rare,8,NaN
239,Spain,Bisexual women,b1_a,"In your opinion, how widespread is offensive l...",Don`t know,4,[0]
240,Spain,Bisexual men,b1_a,"In your opinion, how widespread is offensive l...",Very widespread,10,NaN
241,Spain,Bisexual men,b1_a,"In your opinion, how widespread is offensive l...",Fairly widespread,32,NaN
242,Spain,Bisexual men,b1_a,"In your opinion, how widespread is offensive l...",Fairly rare,41,NaN
243,Spain,Bisexual men,b1_a,"In your opinion, how widespread is offensive l...",Very rare,15,NaN
244,Spain,Bisexual men,b1_a,"In your opinion, how widespread is offensive l...",Don`t know,2,[0]
245,Spain,Transgender,b1_a,"In your opinion, how widespread is offensive l...",Very widespread,9,NaN
246,Spain,Transgender,b1_a,"In your opinion, how widespread is offensive l...",Fairly widespread,36,NaN
247,Spain,Transgender,b1_a,"In your opinion, how widespread is offensive l...",Fairly rare,34,NaN
248,Spain,Transgender,b1_a,"In your opinion, how widespread is offensive l...",Very rare,15,NaN
249,Spain,Transgender,b1_a,"In your opinion, how widespread is offensive l...",Don`t know,5,[0]
575,Romania,Lesbian,b1_a,"In your opinion, how widespread is offensive l...",Very widespread,42,NaN
576,Romania,Lesbian,b1_a,"In your opinion, how widespread is offensive l...",Fairly widespread,34,NaN
577,Romania,Lesbian,b1_a,"In your opinion, how widespread is offensive l...",Fairly rare,12,[0]
578,Romania,Lesbian,b1_a,"In your opinion, how widespread is offensive l...",Very rare,4,[0]
579,Romania,Lesbian,b1_a,"In your opinion, how widespread is offensive l...",Don`t know,8,[0]
...,...,...,...,...,...,...,...
33910,Romania,Bisexual women,openness_cat4,4 levels of being open about LGBT background *,Fairly open,6,[0]
33911,Romania,Bisexual women,openness_cat4,4 levels of being open about LGBT background *,Very open,2,[0]
33912,Romania,Bisexual men,openness_cat4,4 levels of being open about LGBT background *,Never Open,92,NaN
33913,Romania,Bisexual men,openness_cat4,4 levels of being open about LGBT background *,Rarely Open,4,[0]
33914,Romania,Bisexual men,openness_cat4,4 levels of being open about LGBT background *,Fairly open,2,[0]
33915,Romania,Bisexual men,openness_cat4,4 levels of being open about LGBT background *,Very open,2,[0]
33916,Romania,Transgender,openness_cat4,4 levels of being open about LGBT background *,Never Open,80,NaN
33917,Romania,Transgender,openness_cat4,4 levels of being open about LGBT background *,Rarely Open,10,[0]
33918,Romania,Transgender,openness_cat4,4 levels of being open about LGBT background *,Fairly open,7,[0]
33919,Romania,Transgender,openness_cat4,4 levels of being open about LGBT background *,Very open,4,[0]
33980,United Kingdom,Lesbian,openness_cat4,4 levels of being open about LGBT background *,Never Open,12,NaN
33981,United Kingdom,Lesbian,openness_cat4,4 levels of being open about LGBT background *,Rarely Open,20,NaN
33982,United Kingdom,Lesbian,openness_cat4,4 levels of being open about LGBT background *,Fairly open,23,NaN
33983,United Kingdom,Lesbian,openness_cat4,4 levels of being open about LGBT background *,Very open,46,NaN
33984,United Kingdom,Gay,openness_cat4,4 levels of being open about LGBT background *,Never Open,13,NaN
33985,United Kingdom,Gay,openness_cat4,4 levels of being open about LGBT background *,Rarely Open,16,NaN
33986,United Kingdom,Gay,openness_cat4,4 levels of being open about LGBT background *,Fairly open,22,NaN
33987,United Kingdom,Gay,openness_cat4,4 levels of being open about LGBT background *,Very open,48,NaN
33988,United Kingdom,Bisexual women,openness_cat4,4 levels of being open about LGBT background *,Never Open,43,NaN
33989,United Kingdom,Bisexual women,openness_cat4,4 levels of being open about LGBT background *,Rarely Open,28,NaN
33990,United Kingdom,Bisexual women,openness_cat4,4 levels of being open about LGBT background *,Fairly open,16,NaN
33991,United Kingdom,Bisexual women,openness_cat4,4 levels of being open about LGBT background *,Very open,13,NaN
33992,United Kingdom,Bisexual men,openness_cat4,4 levels of being open about LGBT background *,Never Open,54,NaN
33993,United Kingdom,Bisexual men,openness_cat4,4 levels of being open about LGBT background *,Rarely Open,21,NaN
33994,United Kingdom,Bisexual men,openness_cat4,4 levels of being open about LGBT background *,Fairly open,10,NaN
33995,United Kingdom,Bisexual men,openness_cat4,4 levels of being open about LGBT background *,Very open,15,NaN
33996,United Kingdom,Transgender,openness_cat4,4 levels of being open about LGBT background *,Never Open,38,NaN
33997,United Kingdom,Transgender,openness_cat4,4 levels of being open about LGBT background *,Rarely Open,23,NaN
33998,United Kingdom,Transgender,openness_cat4,4 levels of being open about LGBT background *,Fairly open,15,NaN
33999,United Kingdom,Transgender,openness_cat4,4 levels of being open about LGBT background *,Very open,25,NaN

In [26]:
#Select social-based questions that focuses on daily life aspects
questions = [ "In your opinion, how many people know that you are L, G, B or T? Friends?" ]
picked_questions = dailylife[dailylife.question_label.isin(questions)]
picked_questions

,CountryCode,subset,question_code,question_label,answer,percentage,notes
18444,Austria,Lesbian,g2_b,"In your opinion, how many people know that you...",None,1,[0]
18445,Austria,Lesbian,g2_b,"In your opinion, how many people know that you...",A few,6,NaN
18446,Austria,Lesbian,g2_b,"In your opinion, how many people know that you...",Most,23,NaN
18447,Austria,Lesbian,g2_b,"In your opinion, how many people know that you...",All,71,NaN
18448,Austria,Lesbian,g2_b,"In your opinion, how many people know that you...",Don`t know,0,[0]
18449,Austria,Gay,g2_b,"In your opinion, how many people know that you...",None,1,NaN
18450,Austria,Gay,g2_b,"In your opinion, how many people know that you...",A few,16,NaN
18451,Austria,Gay,g2_b,"In your opinion, how many people know that you...",Most,27,NaN
18452,Austria,Gay,g2_b,"In your opinion, how many people know that you...",All,55,NaN
18453,Austria,Gay,g2_b,"In your opinion, how many people know that you...",Don`t know,1,[0]
18454,Austria,Bisexual women,g2_b,"In your opinion, how many people know that you...",None,2,[0]
18455,Austria,Bisexual women,g2_b,"In your opinion, how many people know that you...",A few,23,NaN
18456,Austria,Bisexual women,g2_b,"In your opinion, how many people know that you...",Most,38,NaN
18457,Austria,Bisexual women,g2_b,"In your opinion, how many people know that you...",All,35,NaN
18458,Austria,Bisexual women,g2_b,"In your opinion, how many people know that you...",Don`t know,1,[0]
18459,Austria,Bisexual men,g2_b,"In your opinion, how many people know that you...",None,19,NaN
18460,Austria,Bisexual men,g2_b,"In your opinion, how many people know that you...",A few,42,NaN
18461,Austria,Bisexual men,g2_b,"In your opinion, how many people know that you...",Most,19,NaN
18462,Austria,Bisexual men,g2_b,"In your opinion, how many people know that you...",All,17,NaN
18463,Austria,Bisexual men,g2_b,"In your opinion, how many people know that you...",Don`t know,3,[0]
18464,Austria,Transgender,g2_b,"In your opinion, how many people know that you...",None,11,[0]
18465,Austria,Transgender,g2_b,"In your opinion, how many people know that you...",A few,31,NaN
18466,Austria,Transgender,g2_b,"In your opinion, how many people know that you...",Most,20,NaN
18467,Austria,Transgender,g2_b,"In your opinion, how many people know that you...",All,36,NaN
18468,Austria,Transgender,g2_b,"In your opinion, how many people know that you...",Don`t know,2,[0]
18469,Belgium,Lesbian,g2_b,"In your opinion, how many people know that you...",None,1,[0]
18470,Belgium,Lesbian,g2_b,"In your opinion, how many people know that you...",A few,6,NaN
18471,Belgium,Lesbian,g2_b,"In your opinion, how many people know that you...",Most,22,NaN
18472,Belgium,Lesbian,g2_b,"In your opinion, how many people know that you...",All,71,NaN
18473,Belgium,Lesbian,g2_b,"In your opinion, how many people know that you...",Don`t know,0,[0]
...,...,...,...,...,...,...,...
19139,United Kingdom,Transgender,g2_b,"In your opinion, how many people know that you...",None,7,NaN
19140,United Kingdom,Transgender,g2_b,"In your opinion, how many people know that you...",A few,31,NaN
19141,United Kingdom,Transgender,g2_b,"In your opinion, how many people know that you...",Most,29,NaN
19142,United Kingdom,Transgender,g2_b,"In your opinion, how many people know that you...",All,32,NaN
19143,United Kingdom,Transgender,g2_b,"In your opinion, how many people know that you...",Don`t know,1,[0]
19144,Average,Lesbian,g2_b,"In your opinion, how many people know that you...",None,1,NaN
19145,Average,Lesbian,g2_b,"In your opinion, how many people know that you...",A few,13,NaN
19146,Average,Lesbian,g2_b,"In your opinion, how many people know that you...",Most,27,NaN
19147,Average,Lesbian,g2_b,"In your opinion, how many people know that you...",All,59,NaN
19148,Average,Lesbian,g2_b,"In your opinion, how many people know that you...",Don`t know,0,NaN
19149,Average,Gay,g2_b,"In your opinion, how many people know that you...",None,3,NaN
19150,Average,Gay,g2_b,"In your opinion, how many people know that you...",A few,18,NaN
19151,Average,Gay,g2_b,"In your opinion, how many people know that you...",Most,27,NaN
19152,Average,Gay,g2_b,"In your opinion, how many people know that you...",All,51,NaN
19153,Average,Gay,g2_b,"In your opinion, how many people know that you...",Don`t know,1,NaN
19154,Average,Bisexual women,g2_b,"In your opinion, how many people know that you...",None,3,NaN
19155,Average,Bisexual women,g2_b,"In your opinion, how many people know that you...",A few,30,NaN
19156,Average,Bisexual women,g2_b,"In your opinion, how many people know that you...",Most,37,NaN
19157,Average,Bisexual women,g2_b,"In your opinion, how many people know that you...",All,29,NaN
19158,Average,Bisexual women,g2_b,"In your opinion, how many people know that you...",Don`t know,1,NaN
19159,Average,Bisexual men,g2_b,"In your opinion, how many people know that you...",None,17,NaN
19160,Average,Bisexual men,g2_b,"In your opinion, how many people know that you...",A few,45,NaN
19161,Average,Bisexual men,g2_b,"In your opinion, how many people know that you...",Most,21,NaN
19162,Average,Bisexual men,g2_b,"In your opinion, how many people know that you...",All,15,NaN
19163,Average,Bisexual men,g2_b,"In your opinion, how many people know that you...",Don`t know,2,NaN
19164,Average,Transgender,g2_b,"In your opinion, how many people know that you...",None,12,NaN
19165,Average,Transgender,g2_b,"In your opinion, how many people know that you...",A few,34,NaN
19166,Average,Transgender,g2_b,"In your opinion, how many people know that you...",Most,23,NaN
19167,Average,Transgender,g2_b,"In your opinion, how many people know that you...",All,28,NaN
19168,Average,Transgender,g2_b,"In your opinion, how many people know that you...",Don`t know,3,NaN

In [27]:
uk = picked_questions[picked_questions["CountryCode"] == "United Kingdom"]
uk

,CountryCode,subset,question_code,question_label,answer,percentage,notes
19119,United Kingdom,Lesbian,g2_b,"In your opinion, how many people know that you...",None,1,[0]
19120,United Kingdom,Lesbian,g2_b,"In your opinion, how many people know that you...",A few,6,NaN
19121,United Kingdom,Lesbian,g2_b,"In your opinion, how many people know that you...",Most,27,NaN
19122,United Kingdom,Lesbian,g2_b,"In your opinion, how many people know that you...",All,66,NaN
19123,United Kingdom,Lesbian,g2_b,"In your opinion, how many people know that you...",Don`t know,0,[0]
19124,United Kingdom,Gay,g2_b,"In your opinion, how many people know that you...",None,1,NaN
19125,United Kingdom,Gay,g2_b,"In your opinion, how many people know that you...",A few,10,NaN
19126,United Kingdom,Gay,g2_b,"In your opinion, how many people know that you...",Most,24,NaN
19127,United Kingdom,Gay,g2_b,"In your opinion, how many people know that you...",All,65,NaN
19128,United Kingdom,Gay,g2_b,"In your opinion, how many people know that you...",Don`t know,0,[0]
19129,United Kingdom,Bisexual women,g2_b,"In your opinion, how many people know that you...",None,3,[0]
19130,United Kingdom,Bisexual women,g2_b,"In your opinion, how many people know that you...",A few,27,NaN
19131,United Kingdom,Bisexual women,g2_b,"In your opinion, how many people know that you...",Most,41,NaN
19132,United Kingdom,Bisexual women,g2_b,"In your opinion, how many people know that you...",All,28,NaN
19133,United Kingdom,Bisexual women,g2_b,"In your opinion, how many people know that you...",Don`t know,0,[0]
19134,United Kingdom,Bisexual men,g2_b,"In your opinion, how many people know that you...",None,8,NaN
19135,United Kingdom,Bisexual men,g2_b,"In your opinion, how many people know that you...",A few,37,NaN
19136,United Kingdom,Bisexual men,g2_b,"In your opinion, how many people know that you...",Most,28,NaN
19137,United Kingdom,Bisexual men,g2_b,"In your opinion, how many people know that you...",All,26,NaN
19138,United Kingdom,Bisexual men,g2_b,"In your opinion, how many people know that you...",Don`t know,1,[0]
19139,United Kingdom,Transgender,g2_b,"In your opinion, how many people know that you...",None,7,NaN
19140,United Kingdom,Transgender,g2_b,"In your opinion, how many people know that you...",A few,31,NaN
19141,United Kingdom,Transgender,g2_b,"In your opinion, how many people know that you...",Most,29,NaN
19142,United Kingdom,Transgender,g2_b,"In your opinion, how many people know that you...",All,32,NaN
19143,United Kingdom,Transgender,g2_b,"In your opinion, how many people know that you...",Don`t know,1,[0]

In [37]:
uk_by_subset = uk.groupby(["subset", "answer"]).percentage.sum()
uk_by_subset

subset          answer
Bisexual men    A few         37
                All           26
                Don`t know     1
                Most          28
                None           8
Bisexual women  A few         27
                All           28
                Don`t know     0
                Most          41
                None           3
Gay             A few         10
                All           65
                Don`t know     0
                Most          24
                None           1
Lesbian         A few          6
                All           66
                Don`t know     0
                Most          27
                None           1
Transgender     A few         31
                All           32
                Don`t know     1
                Most          29
                None           7
Name: percentage, dtype: object

In [40]:
uk_by_subset = pd.DataFrame(uk_by_subset.unstack())
uk_by_subset

               percentage
answer              A few All Don`t know Most None
subset
Bisexual men           37  26          1   28    8
Bisexual women         27  28          0   41    3
Gay                    10  65          0   24    1
Lesbian                 6  66          0   27    1
Transgender            31  32          1   29    7

In [41]:
uk_by_subset.groupby(['subset','answer']).sum().unstack(fill_value=0).plot.bar(figsize = (30,10), width = 1)
plt.title("Survey Responses in UK")
plt.grid()

TypeError: Empty 'DataFrame': no numeric data to plot